import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Product } from '../../../core/models/product.model';
import { WhatsAppService } from '../../../core/services/whatsapp.service';

@Component({
  selector: 'app-product-card', standalone: true, imports: [RouterLink, CommonModule],
  template: `<article class="product-card"><a class="image-wrap" [routerLink]="['/shop', product.id]"><img [src]="product.image" [alt]="product.name + ' fashion illustration'" loading="lazy"><span class="new-tag" *ngIf="product.isNew">JUST IN</span><span class="image-arrow" aria-hidden="true">↗</span></a><div class="card-copy"><div class="card-title"><div><span class="category">{{ product.category }}</span><h3><a [routerLink]="['/shop', product.id]">{{ product.name }}</a></h3></div><span class="price">{{ whatsapp.formatPrice(product.price) }}</span></div><div class="sizes"><span>AVAILABLE SIZES</span><span>{{ product.sizes.join(' · ') }}</span></div><div class="card-actions"><a [routerLink]="['/shop', product.id]">View details <span>↗</span></a><button type="button" (click)="whatsapp.enquire(product)">WhatsApp enquiry</button></div></div></article>`,
  styles: [`:host { display:block; } .product-card { min-width:0; } .image-wrap { height:clamp(235px,29vw,380px); background:#e5e0d5; position:relative; display:block; overflow:hidden; color:#1d1c18; } .image-wrap img { width:100%;height:100%;object-fit:cover;display:block;transition:transform .55s cubic-bezier(.2,.7,.2,1); } .product-card:hover .image-wrap img { transform:scale(1.035); } .new-tag { position:absolute;top:13px;left:13px;padding:7px 9px;background:#171714;color:#e4cd98;font-size:8px;letter-spacing:.12em; } .image-arrow { position:absolute;right:13px;bottom:13px;width:34px;height:34px;background:#f7f5ef;display:grid;place-items:center;opacity:0;transition:opacity .2s; } .product-card:hover .image-arrow { opacity:1; } .card-copy { padding-top:14px; } .card-title { display:flex;justify-content:space-between;gap:12px;align-items:flex-start; } .category { color:#928d80;text-transform:uppercase;letter-spacing:.15em;font-size:8px; } h3 { margin:5px 0 0;font:500 18px 'Segoe UI',sans-serif; } h3 a { color:#24231f;text-decoration:none; } .price { white-space:nowrap;font-size:12px;font-weight:600;color:#24231f;margin-top:14px; } .sizes { display:flex;justify-content:space-between;gap:6px;margin-top:13px;padding-top:10px;border-top:1px solid #d8d3c8;color:#79766e;font-size:8px; } .sizes span:first-child { letter-spacing:.11em; } .card-actions { display:flex;justify-content:space-between;align-items:center;margin-top:12px; } .card-actions a { color:#26251f;font-size:10px;text-decoration:none; } .card-actions a span { color:#9f8249;margin-left:4px; } .card-actions button { border:0;background:transparent;color:#7c683e;font:500 9px 'Segoe UI',sans-serif;cursor:pointer;padding:6px 0; } @media(max-width:480px) { .image-wrap{height:230px}.card-actions button{font-size:8px} h3{font-size:16px}.sizes{font-size:7px} }`]
})
export class ProductCardComponent { @Input({ required: true }) product!: Product; constructor(readonly whatsapp: WhatsAppService) {} }
